from normal_learning import experiment

experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:0.9", clip=0.9)
experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:0.95", clip=0.95)
experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:1.0", clip=1.0)
experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:1.05", clip=1.05)
experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:1.1", clip=1.1)
experiment(epochs=100, mode="multiclass", anomaly_type='random_lines', anomaly_amount=1, prediction_only=False, experiment="binary_clip:1.15", clip=1.15)
# experiment(anomaly_type='insert_words', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='insert_words', anomaly_amount=2, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='insert_words', anomaly_amount=3, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='insert_words', anomaly_amount=4, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='remove_words', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='remove_words', anomaly_amount=2, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='replace_words', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='replace_words', anomaly_amount=2, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='duplicate_lines', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='duplicate_lines', anomaly_amount=2, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='duplicate_lines', anomaly_amount=3, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='delete_lines', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='delete_lines', anomaly_amount=2, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='shuffle', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='no_anomaly', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)
# experiment(anomaly_type='reverse_order', anomaly_amount=1, experiment="multiclass", mode="multiclass", prediction_only=True)