from normal_learning import experiment

experiment(anomaly_type="random_lines")
experiment(anomaly_type="random_lines", clip=1.18, experiment="clip=1.18")
experiment(anomaly_type="random_lines", clip=1.19, experiment="clip=1.19")
experiment(anomaly_type="random_lines", clip=1.2, experiment="clip=1.2")
experiment(anomaly_type="random_lines", clip=1.21, experiment="clip=1.21")
experiment(anomaly_type="random_lines", clip=1.22, experiment="clip=1.22")
experiment(anomaly_type="random_lines", clip=1.23, experiment="clip=1.23")
experiment(anomaly_type="random_lines", clip=1.24, experiment="clip=1.24")
experiment(anomaly_type="random_lines", clip=1.25, experiment="clip=1.25")
experiment(anomaly_type="random_lines", clip=1.26, experiment="clip=1.26")
experiment(anomaly_type="random_lines", clip=1.27, experiment="clip=1.27")
experiment(anomaly_type="random_lines", clip=1.28, experiment="clip=1.28")

# experiment(anomaly_type="insert_words", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=2, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=3, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=4, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=5, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=6, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=7, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=8, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="insert_words", anomaly_amount=9, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="remove_words", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="remove_words", anomaly_amount=2, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="replace_words", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="replace_words", anomaly_amount=2, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="duplicate_lines", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="delete_lines", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="shuffle", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="no_anomaly", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")
# experiment(anomaly_type="reverse_order", anomaly_amount=1, anomaly_only=True, label_encoder="encoder_normal.pickle")